version: '2.0'
services:

  postgres:
    image: postgres:9.5
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${TT_DB_USER}
      POSTGRES_PASSWORD: ${TT_DB_PASSWORD}
      POSTGRES_DB: ${TT_DB_NAME}
    networks:
      default:

  server:
    build: .
    image: tt_server
    restart: unless-stopped
    networks:
      default:
    ports:
      - "8000:8000"
    links:
      - postgres

  client:
    image: tt_client
    restart: unless-stopped
    networks:
      default:

