# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 20:32
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.hashers import make_password


def create_admin_user(apps, schema_editor):
    User = apps.get_registered_model('auth', 'User')
    admin = User(
       username='admin',
       email='admin@localhost',
       password=make_password('admin'),
       is_superuser=True,
       is_staff=True
    )
    admin.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('auth', '0001_initial'),
     ]

    operations = [
        migrations.DeleteModel(
            name='Server',
        ),
        migrations.RemoveField(
            model_name='uptime',
            name='server',
        ),
        migrations.DeleteModel(
            name='Uptime',
        ),
        migrations.RunPython(create_admin_user),
    ]
